import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const project = await prisma.project.findUnique({
    where: { id: "demo-xinghe" },
  });
  if (!project) {
    throw new Error("未找到项目「星河碰撞」。请先执行 pnpm db:seed:world-demo");
  }

  const episode = await prisma.episode.findUnique({
    where: { id: "demo-ep-01" },
  });
  if (!episode) {
    throw new Error("未找到 Episode 1。请先执行 pnpm db:seed:story-demo");
  }

  const script = await prisma.script.findUnique({
    where: { episodeId: episode.id },
    include: {
      scenes: {
        orderBy: { number: "asc" },
        include: { blocks: { orderBy: { order: "asc" } } },
      },
    },
  });
  if (!script || script.scenes.length < 3) {
    throw new Error("未找到 Episode 1 的完整剧本。请先执行 pnpm db:seed:script-demo");
  }

  const shen = await prisma.character.findUnique({ where: { id: "demo-char-shenxinghe" } });
  const taixu = await prisma.character.findUnique({ where: { id: "demo-char-taixu" } });
  const aer = await prisma.character.findUnique({ where: { id: "demo-char-aer" } });
  if (!shen || !taixu || !aer) {
    throw new Error("未找到沈星河 / 太虚真人 / 艾尔。请先执行 pnpm db:seed:character-demo");
  }

  const [scene1, scene2, scene3] = script.scenes;
  const b = (scene: (typeof script.scenes)[number], order: number) =>
    scene.blocks.find((item) => item.order === order)?.id ?? scene.blocks[0]?.id ?? null;

  const storyboard = await prisma.storyboard.upsert({
    where: { episodeId: episode.id },
    update: {
      title: "星系碰撞 · 分镜",
      description: "问天宗夜课被星裂打断，镜头从宗门日常推进到第一次接触的视觉悬念。",
      status: "READY",
      version: 1,
      sourceScriptVersion: script.version,
      totalDurationSeconds: 61,
    },
    create: {
      id: "demo-storyboard-ep01",
      projectId: project.id,
      episodeId: episode.id,
      title: "星系碰撞 · 分镜",
      description: "问天宗夜课被星裂打断，镜头从宗门日常推进到第一次接触的视觉悬念。",
      status: "READY",
      version: 1,
      sourceScriptVersion: script.version,
      totalDurationSeconds: 61,
    },
  });

  await prisma.storyboardShot.deleteMany({ where: { storyboardId: storyboard.id } });

  await prisma.storyboardShot.createMany({
    data: [
      {
        storyboardId: storyboard.id,
        sceneId: scene1.id,
        scriptBlockId: b(scene1, 1),
        shotNumber: 1,
        shotType: "WIDE",
        shotSize: "WIDE",
        cameraMovement: "STATIC",
        cameraAngle: "EYE_LEVEL",
        composition: "广场灯火为前景，夜空占上半",
        visualDescription: "问天宗外门广场远景。弟子列阵诵经，星图在空中缓慢旋转。",
        characterIds: [shen.id],
        location: scene1.location,
        action: "弟子夜课，沈星河站在队列外侧",
        durationSeconds: 6,
        transition: "FADE_IN",
        lighting: "冷青夜灯",
        mood: "平静将破",
        visualStyle: "科幻修仙",
        imagePrompt: "wide night courtyard of a cultivation sect, disciples in rows, rotating star map in the sky, cinematic",
        videoPrompt: "static wide establishing shot of a night sect courtyard, star map slowly rotating",
        negativePrompt: "text, watermark, modern city",
        continuityNotes: "沈星河位于画面右侧队列外",
        metadata: { sourceScriptBlockIds: [b(scene1, 1)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene1.id,
        scriptBlockId: b(scene1, 2),
        shotNumber: 2,
        shotType: "MEDIUM",
        shotSize: "MEDIUM",
        cameraMovement: "DOLLY_IN",
        cameraAngle: "LOW_ANGLE",
        visualDescription: "沈星河抬头，木剑几乎滑落。摄像机缓慢推进。",
        characterIds: [shen.id],
        location: scene1.location,
        action: "抬头望向星裂",
        durationSeconds: 4,
        transition: "CUT",
        lighting: "星裂白光开始压过灯火",
        mood: "震惊",
        visualStyle: "科幻修仙",
        imagePrompt: "medium shot young cultivator looking up, wooden sword slipping, cosmic crack lighting his face",
        videoPrompt: "slow dolly in as the youth looks up, wooden sword almost falling",
        negativePrompt: "text, watermark",
        continuityNotes: "人物仍在广场右侧，面向天空",
        metadata: { sourceScriptBlockIds: [b(scene1, 2)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene1.id,
        scriptBlockId: b(scene1, 3),
        shotNumber: 3,
        shotType: "CLOSE_UP",
        shotSize: "CLOSE_UP",
        cameraMovement: "STATIC",
        cameraAngle: "EYE_LEVEL",
        visualDescription: "眼睛特写，星裂倒影拉成一条白线。",
        characterIds: [shen.id],
        location: scene1.location,
        action: "瞳孔收缩",
        durationSeconds: 2,
        transition: "CUT",
        lighting: "高反差星光",
        mood: "敬畏",
        visualStyle: "科幻修仙",
        imagePrompt: "extreme close up of eyes reflecting a cosmic crack, cinematic lighting",
        videoPrompt: "static close up, crack reflection stretching across the pupil",
        negativePrompt: "text, watermark",
        continuityNotes: "视线方向朝上",
        metadata: { sourceScriptBlockIds: [b(scene1, 3)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene1.id,
        scriptBlockId: b(scene1, 4),
        shotNumber: 4,
        shotType: "OVER_SHOULDER",
        shotSize: "MEDIUM",
        cameraMovement: "PAN",
        cameraAngle: "EYE_LEVEL",
        visualDescription: "从沈星河肩后看见天空裂缝扩大。",
        characterIds: [shen.id],
        location: scene1.location,
        action: "凝视天空",
        dialogue: "那是什么？",
        durationSeconds: 4,
        transition: "CUT",
        lighting: "裂缝强光",
        mood: "不安",
        visualStyle: "科幻修仙",
        imagePrompt: "over shoulder shot of a youth facing a giant sky crack above a sect courtyard",
        videoPrompt: "slow pan from the shoulder to the expanding sky crack",
        negativePrompt: "text, watermark",
        continuityNotes: "轴线：人物右肩在画面左下",
        metadata: { sourceScriptBlockIds: [b(scene1, 4)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene2.id,
        scriptBlockId: b(scene2, 1),
        shotNumber: 5,
        shotType: "WIDE",
        shotSize: "WIDE",
        cameraMovement: "TRACKING",
        cameraAngle: "LOW_ANGLE",
        visualDescription: "太虚真人踏出观星台，白发被乱流掀起。",
        characterIds: [taixu.id],
        location: scene2.location,
        action: "踏出观星台并按住虚空",
        durationSeconds: 5,
        transition: "CUT",
        lighting: "乱流与禁制碎光",
        mood: "凝重",
        visualStyle: "科幻修仙",
        imagePrompt: "wide tracking shot of an old immortal on an observatory, white hair in storm, night sky cracked",
        videoPrompt: "tracking wide shot as the master steps onto the observatory platform",
        negativePrompt: "text, watermark",
        continuityNotes: "观星台在画面中层，天空裂缝仍在上方",
        metadata: { sourceScriptBlockIds: [b(scene2, 1)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene2.id,
        scriptBlockId: b(scene2, 2),
        shotNumber: 6,
        shotType: "MEDIUM",
        shotSize: "MEDIUM",
        cameraMovement: "STATIC",
        cameraAngle: "EYE_LEVEL",
        visualDescription: "太虚真人正面中景，说出星轨被改写。",
        characterIds: [taixu.id],
        location: scene2.location,
        dialogue: "星轨被人改写了。不是天灾。",
        durationSeconds: 4,
        transition: "CUT",
        lighting: "侧面星裂光",
        mood: "决断",
        visualStyle: "科幻修仙",
        imagePrompt: "medium shot aged immortal speaking grimly, cosmic light on one side of the face",
        videoPrompt: "static medium shot, mouth synced to the line",
        negativePrompt: "text, watermark",
        continuityNotes: "面向镜头略偏左，视线仍对天空",
        metadata: { sourceScriptBlockIds: [b(scene2, 2)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene2.id,
        scriptBlockId: b(scene2, 3),
        shotNumber: 7,
        shotType: "CLOSE_UP",
        shotSize: "CLOSE_UP",
        cameraMovement: "DOLLY_IN",
        cameraAngle: "EYE_LEVEL",
        visualDescription: "沈星河请命下山。",
        characterIds: [shen.id],
        location: scene2.location,
        dialogue: "师父，我去看。",
        durationSeconds: 3,
        transition: "CUT",
        lighting: "暖灯与冷星光对冲",
        mood: "决心",
        visualStyle: "科幻修仙",
        imagePrompt: "close up determined young cultivator, mixed warm lantern and cold starlight",
        videoPrompt: "gentle dolly in on the youth saying he will go",
        negativePrompt: "text, watermark",
        continuityNotes: "沈星河在师父右侧",
        metadata: { sourceScriptBlockIds: [b(scene2, 3)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene2.id,
        scriptBlockId: b(scene2, 4),
        shotNumber: 8,
        shotType: "AERIAL",
        shotSize: "EXTREME_WIDE",
        cameraMovement: "CRANE_DOWN",
        cameraAngle: "BIRDS_EYE",
        visualDescription: "俯拍观星台，宗门灯火在星裂下极小。",
        characterIds: [shen.id, taixu.id],
        location: scene2.location,
        durationSeconds: 4,
        transition: "DISSOLVE",
        lighting: "巨大裂缝压过灯火",
        mood: "渺小",
        visualStyle: "科幻修仙",
        imagePrompt: "bird's eye view of a tiny observatory under a gigantic cosmic crack",
        videoPrompt: "crane down from sky crack to the small observatory lights",
        negativePrompt: "text, watermark",
        continuityNotes: "人物位置可辨：右侧青年，中央师父",
        metadata: { sourceScriptBlockIds: [b(scene2, 4)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene2.id,
        scriptBlockId: b(scene2, 5),
        shotNumber: 9,
        shotType: "MEDIUM",
        shotSize: "MEDIUM",
        cameraMovement: "STATIC",
        cameraAngle: "HIGH_ANGLE",
        visualDescription: "太虚没有阻止。沈星河转身下山。",
        characterIds: [shen.id, taixu.id],
        location: scene2.location,
        narration: "有些真相，必须由还愿意抬头的人去碰。",
        durationSeconds: 4,
        transition: "CUT",
        lighting: "灯火渐远",
        mood: "沉重",
        visualStyle: "科幻修仙",
        imagePrompt: "high angle medium shot, master standing still, youth turning away down the mountain",
        videoPrompt: "static high angle, youth turns and leaves, master does not stop him",
        negativePrompt: "text, watermark",
        continuityNotes: "沈星河向画面下方离开",
        metadata: { sourceScriptBlockIds: [b(scene2, 5)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene3.id,
        scriptBlockId: b(scene3, 1),
        shotNumber: 10,
        shotType: "WIDE",
        shotSize: "WIDE",
        cameraMovement: "TRACKING",
        cameraAngle: "EYE_LEVEL",
        visualDescription: "沈星河冲过荒原，光坠落砸出焦黑深坑。",
        characterIds: [shen.id],
        location: scene3.location,
        action: "奔跑追上坠落的光",
        durationSeconds: 5,
        transition: "SMASH_CUT",
        lighting: "坠落光柱",
        mood: "紧迫",
        visualStyle: "科幻修仙",
        imagePrompt: "wide tracking shot of a youth running across a barren starfield, a beam of light crashing into the ground",
        videoPrompt: "tracking wide shot following the runner toward a crashing light",
        negativePrompt: "text, watermark",
        continuityNotes: "人物从画面左向右追光",
        metadata: { sourceScriptBlockIds: [b(scene3, 1)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene3.id,
        scriptBlockId: b(scene3, 2),
        shotNumber: 11,
        shotType: "INSERT",
        shotSize: "CLOSE_UP",
        cameraMovement: "STATIC",
        cameraAngle: "OVERHEAD",
        visualDescription: "残臂内侧的星环议会徽记特写。",
        characterIds: [],
        location: scene3.location,
        action: "义体残臂闪烁",
        durationSeconds: 3,
        transition: "CUT",
        lighting: "机械冷光",
        mood: "异质",
        visualStyle: "科幻修仙",
        imagePrompt: "insert close up of a cybernetic arm fragment with a star-ring parliament emblem, overhead lighting",
        videoPrompt: "static insert of a flickering prosthetic arm fragment",
        negativePrompt: "text, watermark",
        continuityNotes: "下一镜切回沈星河握剑的手",
        metadata: { sourceScriptBlockIds: [b(scene3, 2)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene3.id,
        scriptBlockId: b(scene3, 2),
        shotNumber: 12,
        shotType: "CLOSE_UP",
        shotSize: "CLOSE_UP",
        cameraMovement: "STATIC",
        cameraAngle: "EYE_LEVEL",
        visualDescription: "沈星河握紧木剑的手指。同一段落拆成第二镜。",
        characterIds: [shen.id],
        location: scene3.location,
        action: "握紧木剑",
        durationSeconds: 2,
        transition: "CUT",
        lighting: "坑沿余烬",
        mood: "警惕",
        visualStyle: "科幻修仙",
        imagePrompt: "close up of a hand gripping a wooden sword, embers in background",
        videoPrompt: "static close up fingers tightening on the sword",
        negativePrompt: "text, watermark",
        continuityNotes: "与上一镜匹配切：残臂到握剑",
        metadata: { sourceScriptBlockIds: [b(scene3, 2)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene3.id,
        scriptBlockId: b(scene3, 3),
        shotNumber: 13,
        shotType: "MEDIUM",
        shotSize: "MEDIUM",
        cameraMovement: "DOLLY_IN",
        cameraAngle: "LOW_ANGLE",
        visualDescription: "沈星河对着残骸发问。",
        characterIds: [shen.id],
        location: scene3.location,
        dialogue: "这不是灵器……这是什么人？",
        durationSeconds: 4,
        transition: "CUT",
        lighting: "黎明前灰蓝",
        mood: "困惑",
        visualStyle: "科幻修仙",
        imagePrompt: "low angle medium shot youth over a crater, asking what kind of person this is",
        videoPrompt: "slow dolly in on the youth speaking over the wreckage",
        negativePrompt: "text, watermark",
        continuityNotes: "坑在人物前方，视线向下再抬起",
        metadata: { sourceScriptBlockIds: [b(scene3, 3)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene3.id,
        scriptBlockId: b(scene3, 4),
        shotNumber: 14,
        shotType: "WIDE",
        shotSize: "WIDE",
        cameraMovement: "PAN",
        cameraAngle: "EYE_LEVEL",
        visualDescription: "风停。坑外阴影里尚未现身的观察者。",
        characterIds: [shen.id, aer.id],
        location: scene3.location,
        narration: "坑外的阴影里，艾尔尚未开口，但她的观察记录已经开始。",
        durationSeconds: 5,
        transition: "CUT",
        lighting: "阴影与余烬",
        mood: "悬念",
        visualStyle: "科幻修仙",
        imagePrompt: "wide barren crater, youth in foreground, a shadowed cybernetic figure barely visible at the edge",
        videoPrompt: "slow pan from the crater to a shadowed figure beyond the pit",
        negativePrompt: "text, watermark",
        continuityNotes: "艾尔在画面最右侧阴影，尚未露脸",
        metadata: { sourceScriptBlockIds: [b(scene3, 4)].filter(Boolean) },
      },
      {
        storyboardId: storyboard.id,
        sceneId: scene3.id,
        scriptBlockId: b(scene3, 5),
        shotNumber: 15,
        shotType: "OVER_SHOULDER",
        shotSize: "MEDIUM_CLOSE_UP",
        cameraMovement: "STATIC",
        cameraAngle: "EYE_LEVEL",
        visualDescription: "艾尔的第一句接触记录。",
        characterIds: [aer.id, shen.id],
        location: scene3.location,
        dialogue: "接触记录，启动。",
        durationSeconds: 4,
        transition: "FADE_OUT",
        lighting: "义体指示灯微光",
        mood: "冷静",
        visualStyle: "科幻修仙",
        imagePrompt: "over shoulder of a cybernetic woman observing a young cultivator across a crater, cool indicator lights",
        videoPrompt: "static over shoulder, electronic voice line, then fade out",
        negativePrompt: "text, watermark",
        continuityNotes: "沈星河仍在坑边，背对艾尔",
        metadata: { sourceScriptBlockIds: [b(scene3, 5)].filter(Boolean) },
      },
    ],
  });

  console.log("已为「星河碰撞」Season 1 Episode 1 写入 Demo Storyboard（15 shots）。");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
