import { HttpException, HttpStatus } from "@nestjs/common";

export const ErrorCodes = {
  NO_AI_PROVIDER_CONFIGURED: "NO_AI_PROVIDER_CONFIGURED",
  PROVIDER_IN_USE: "PROVIDER_IN_USE",
  ENCRYPTION_KEY_MISSING: "ENCRYPTION_KEY_MISSING",
  PROVIDER_MANAGEMENT_DISABLED: "PROVIDER_MANAGEMENT_DISABLED",
  PROVIDER_NOT_SUPPORTED: "PROVIDER_NOT_SUPPORTED",
  INVALID_API_KEY: "INVALID_API_KEY",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  CHARACTER_NAME_CONFLICT: "CHARACTER_NAME_CONFLICT",
  CHARACTER_NOT_FOUND: "CHARACTER_NOT_FOUND",
  CHARACTER_NOT_IN_PROJECT: "CHARACTER_NOT_IN_PROJECT",
  CIVILIZATION_NOT_IN_PROJECT: "CIVILIZATION_NOT_IN_PROJECT",
  FACTION_NOT_IN_PROJECT: "FACTION_NOT_IN_PROJECT",
  INVALID_CHARACTER_RELATIONSHIP: "INVALID_CHARACTER_RELATIONSHIP",
  DUPLICATE_CHARACTER_RELATIONSHIP: "DUPLICATE_CHARACTER_RELATIONSHIP",
  RELATIONSHIP_NOT_FOUND: "RELATIONSHIP_NOT_FOUND",
  PROVIDER_CAPABILITY_NOT_SUPPORTED: "PROVIDER_CAPABILITY_NOT_SUPPORTED",
  PROVIDER_DISABLED: "PROVIDER_DISABLED",
  PROVIDER_API_KEY_MISSING: "PROVIDER_API_KEY_MISSING",
  MODEL_DISABLED: "MODEL_DISABLED",
  MODEL_CAPABILITY_NOT_SUPPORTED: "MODEL_CAPABILITY_NOT_SUPPORTED",
  MODEL_NOT_IN_PROVIDER: "MODEL_NOT_IN_PROVIDER",
  CAPABILITY_NOT_IMPLEMENTED: "CAPABILITY_NOT_IMPLEMENTED",
  INVALID_AI_CAPABILITY: "INVALID_AI_CAPABILITY",
} as const;

export class AppError extends HttpException {
  readonly code: string;

  constructor(status: HttpStatus, code: string, message: string) {
    super({ statusCode: status, code, message }, status);
    this.code = code;
  }
}
